version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: flowState_db
    restart: always
    environment:
      POSTGRES_USER: marta
      POSTGRES_PASSWORD: holamundo
      POSTGRES_DB: flowState
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
