version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: flowState_db
    restart: always
    environment:
      POSTGRES_USER: marta
      POSTGRES_PASSWORD: holamundo
      POSTGRES_DB: flowState
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowState_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/flowState
      SPRING_DATASOURCE_USERNAME: marta
      SPRING_DATASOURCE_PASSWORD: holamundo
    depends_on:
      - db

volumes:
  pgdata:
